# Generated by Django 5.2.17 on 2026-09-30 18:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('author', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=80, verbose_name='last edited by')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'team doc',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=128)),
                ('mime_type', models.CharField(max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('added_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='teamdocs.docpost')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
