# Generated by Django 5.2.17 on 2026-10-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamdocs', '0001_team_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpost',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='docpost',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docpost',
            name='pinned_by',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
