# Generated by Django 5.2.17 on 2026-09-30 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_photo_low_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=128, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('stage', models.CharField(blank=True, max_length=128)),
                ('progress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(default=dict)),
                ('log', models.JSONField(default=list)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reported_by', models.CharField(blank=True, max_length=80)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_reports', to='inventory.item')),
            ],
            options={
                'ordering': ['-last_seen', '-id'],
            },
        ),
    ]
