# Generated by Django 5.2.17 on 2026-09-24 00:22

import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_normalized', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_normalized', models.CharField(max_length=64, unique=True)),
                ('positions', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_normalized', models.CharField(max_length=64, unique=True)),
                ('sku_display', models.CharField(max_length=64)),
                ('prompt_text', models.TextField(blank=True)),
                ('chatgpt_text', models.TextField(blank=True)),
                ('final_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('sku_normalized', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('intake', 'Intake'), ('ebay draft', 'eBay Draft'), ('ebay review', 'eBay Review'), ('ebay listed', 'eBay Listed'), ('dispo tech store', 'Dispo Tech Store'), ('sold', 'SOLD')], db_index=True, default='intake', max_length=32)),
                ('what_is_it', models.CharField(max_length=255, verbose_name='What is it?')),
                ('ebay_category', models.CharField(blank=True, max_length=255)),
                ('ebay_category_path', models.CharField(blank=True, max_length=512)),
                ('ebay_category_id', models.CharField(blank=True, max_length=32)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Where did it come from?')),
                ('where_it_goes', models.CharField(blank=True, max_length=255, verbose_name='Location / where it goes')),
                ('functional', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=16)),
                ('condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Great', 'Great'), ('Excellent', 'Excellent'), ('Unicorn', 'Unicorn')], max_length=16)),
                ('is_square', models.BooleanField(default=False, verbose_name='Is it a Square item?')),
                ('care_if_square', models.BooleanField(default=False, verbose_name='Do we care about this item?')),
                ('cords_adapters', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='Cords / adapters included?')),
                ('keep_items_together', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='Keep items together?')),
                ('picture_taken', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='Picture')),
                ('power_on', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='Does it power on and stay on?')),
                ('brand_model', models.CharField(blank=True, max_length=255, verbose_name='Brand & model number')),
                ('ram', models.CharField(blank=True, max_length=255, verbose_name='RAM')),
                ('ssd_gb', models.CharField(blank=True, max_length=255, verbose_name='SSD GB')),
                ('cpu', models.CharField(blank=True, max_length=255, verbose_name='CPU')),
                ('os', models.CharField(blank=True, max_length=255, verbose_name='OS')),
                ('compatible_os', models.CharField(blank=True, choices=[('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11'), ('Linux', 'Linux')], max_length=32)),
                ('battery_health', models.CharField(blank=True, max_length=255)),
                ('graphics_card', models.CharField(blank=True, max_length=255)),
                ('screen_resolution', models.CharField(blank=True, max_length=255)),
                ('diagnostics_test_ran', models.BooleanField(default=False)),
                ('wifi_card_installed', models.BooleanField(default=False)),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('ebay_status', models.CharField(blank=True, max_length=255, verbose_name='eBay status')),
                ('in_ebay_room', models.CharField(blank=True, max_length=255, verbose_name='In eBay room')),
                ('what_box', models.CharField(blank=True, max_length=255, verbose_name='What box')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('reviewed', models.PositiveSmallIntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE'), (2, 'SOLD')], default=0)),
                ('ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='inventory_i_status_fd98f1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('sku_normalized', ''), _negated=True)), fields=('sku_normalized',), name='unique_active_sku')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_normalized', models.CharField(db_index=True, max_length=64)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=128)),
                ('mime_type', models.CharField(max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('is_thumb', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['sku_normalized', 'is_thumb', 'id'], name='inventory_p_sku_nor_f0af67_idx')],
            },
        ),
    ]
