# Generated by Django 5.2.17 on 2026-09-24 19:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_normalized', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('restored', 'Restored'), ('photo_added', 'Photo added'), ('photo_removed', 'Photo removed')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.item')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['item', 'created_at'], name='inventory_i_item_id_cdcff8_idx')],
            },
        ),
    ]
