# Generated by Django 5.2.17 on 2026-09-25 03:18

from django.db import migrations, models


def unicorn_to_excellent(apps, schema_editor):
    """The old top grade "Unicorn" is not on the new scale; keep those items at the top."""
    Item = apps.get_model("inventory", "Item")
    IntakeDraft = apps.get_model("inventory", "IntakeDraft")
    Item.objects.filter(condition__iexact="unicorn").update(condition="Excellent")
    for draft in IntakeDraft.objects.all():
        if str((draft.payload or {}).get("condition", "")).lower() == "unicorn":
            draft.payload["condition"] = "Excellent"
            draft.save(update_fields=["payload"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_history'),
    ]

    operations = [
        migrations.RunPython(unicorn_to_excellent, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, choices=[('Scrap', 'Scrap'), ('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Great', 'Great'), ('Excellent', 'Excellent')], max_length=16),
        ),
    ]
