# Generated by Django 5.2.17 on 2026-09-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_condition_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='low_res',
            field=models.BooleanField(default=False),
        ),
    ]
