# Generated by Django 5.2.17 on 2026-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_photo_low_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fcc_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='FCC ID'),
        ),
    ]
