# Generated by Django 5.2.17 on 2026-09-24 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('sku_normalized', models.CharField(blank=True, db_index=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('sold_at', models.DateField(blank=True, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('buyer', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('legacy_source', models.CharField(blank=True, max_length=255)),
                ('legacy_table', models.CharField(blank=True, max_length=255)),
                ('legacy_id', models.CharField(blank=True, max_length=128)),
                ('legacy_location_id', models.CharField(blank=True, max_length=128)),
                ('legacy_category_id', models.CharField(blank=True, max_length=128)),
                ('legacy_payload', models.TextField(blank=True, help_text='The original row, kept for auditing.')),
            ],
            options={
                'ordering': ['-sold_at', '-updated_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'sold_at'], name='archive_arc_status_3ef93c_idx'), models.Index(fields=['legacy_source', 'legacy_table'], name='archive_arc_legacy__14f1e6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('legacy_id', ''), _negated=True), fields=('legacy_source', 'legacy_table', 'legacy_id'), name='unique_legacy_identity')],
            },
        ),
    ]
