# Generated by Django 5.2.17 on 2026-09-24 00:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_normalized', models.CharField(max_length=64, unique=True)),
                ('square_item_id', models.CharField(blank=True, max_length=64)),
                ('square_item_version', models.BigIntegerField(blank=True, null=True)),
                ('square_variation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('square_variation_version', models.BigIntegerField(blank=True, null=True)),
                ('square_image_id', models.CharField(blank=True, max_length=64)),
                ('square_image_photo_id', models.BigIntegerField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_sale_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_inventory_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_origin', models.CharField(blank=True, max_length=16)),
                ('last_correlation_id', models.CharField(blank=True, max_length=64)),
                ('last_local_change_at', models.DateTimeField(blank=True, null=True)),
                ('last_square_change_at', models.DateTimeField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('last_synced_quantity', models.IntegerField(blank=True, null=True)),
                ('last_synced_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'catalog sync record',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sku_normalized', models.CharField(blank=True, max_length=64)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('ondemand', 'On demand')], max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_items_checked', models.IntegerField(default=0)),
                ('issues_detected', models.IntegerField(default=0)),
                ('issues_repaired', models.IntegerField(default=0)),
                ('manual_actions_required', models.IntegerField(default=0)),
                ('api_requests_made', models.IntegerField(default=0)),
                ('api_requests_failed', models.IntegerField(default=0)),
                ('runtime_seconds', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SyncAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('operation', models.CharField(max_length=64)),
                ('sku_normalized', models.CharField(blank=True, db_index=True, max_length=64)),
                ('direction', models.CharField(choices=[('push', 'Pinksheet → Square'), ('pull', 'Square → Pinksheet')], max_length=8)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('skipped', 'Skipped')], max_length=8)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, max_length=32)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('queue_job_id', models.BigIntegerField(blank=True, null=True)),
                ('webhook_id', models.CharField(blank=True, max_length=128)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('request_body_hash', models.CharField(blank=True, max_length=64)),
                ('response_summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('merchant_id', models.CharField(blank=True, max_length=64)),
                ('location_id', models.CharField(blank=True, max_length=64)),
                ('body_hash', models.CharField(max_length=64)),
                ('result_status', models.CharField(blank=True, max_length=16)),
                ('result_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_normalized', models.CharField(blank=True, max_length=64)),
                ('issue_type', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('description', models.TextField()),
                ('pinksheet_value', models.TextField(blank=True)),
                ('square_value', models.TextField(blank=True)),
                ('auto_repairable', models.BooleanField(default=False)),
                ('repair_action', models.CharField(blank=True, max_length=32)),
                ('repair_status', models.CharField(choices=[('pending', 'Pending'), ('auto_repaired', 'Auto-repaired'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('manual_required', 'Needs a person')], default='pending', max_length=16)),
                ('repair_result', models.TextField(blank=True)),
                ('repaired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='squaresync.reconciliationrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('sku_normalized', models.CharField(db_index=True, max_length=64)),
                ('square_order_id', models.CharField(max_length=64)),
                ('square_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_item_quantity', models.PositiveIntegerField(default=1)),
                ('sold_at', models.DateTimeField(db_index=True)),
                ('location_id', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(default='square_pos', max_length=32)),
                ('receipt_number', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-sold_at'],
                'constraints': [models.UniqueConstraint(fields=('square_order_id', 'sku_normalized'), name='unique_sale_line')],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_normalized', models.CharField(max_length=64)),
                ('operation', models.CharField(choices=[('catalog_upsert', 'Catalog update'), ('inventory_set', 'Inventory count'), ('inventory_pull', 'Inventory check'), ('full_sync', 'Full sync')], max_length=32)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('retrying', 'Retrying'), ('dead_letter', 'Gave up')], db_index=True, default='queued', max_length=16)),
                ('rerun', models.BooleanField(default=False, help_text='Changed again while it was being processed.')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=10)),
                ('last_error', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='squaresync__status_e26c8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('sku_normalized', 'operation'), name='unique_job_per_sku_op')],
            },
        ),
    ]
