# Generated by Django 5.2.17 on 2026-09-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squaresync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncauditlog',
            name='direction',
            field=models.CharField(choices=[('push', 'Dispodex → Square'), ('pull', 'Square → Dispodex')], max_length=8),
        ),
    ]
