# Generated by Django 5.2.17 on 2026-09-30 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporter', models.CharField(max_length=80, verbose_name='name')),
                ('sent_by', models.CharField(blank=True, max_length=80, verbose_name='sent from account or device')),
                ('summary', models.CharField(max_length=200, verbose_name='what went wrong')),
                ('details', models.TextField(blank=True, verbose_name='what they were doing')),
                ('page', models.CharField(blank=True, max_length=500)),
                ('browser', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
